services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: EMAIL_HOST_USER
        value: prajapatiayush1222@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: 'gnickkxwymmmpzfu'
